// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHxzBf7AzcoK9hW7YrUoL9PNimLZGr2Ck',
    appId: '1:717510301151:web:fcfd40c339e4da7cdae06a',
    messagingSenderId: '717510301151',
    projectId: 'development-673fa',
    authDomain: 'development-673fa.firebaseapp.com',
    storageBucket: 'development-673fa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEqfw2YsTPMboRasjj5C8lXoP-cIQdlbs',
    appId: '1:717510301151:android:4d2812f8320544c9dae06a',
    messagingSenderId: '717510301151',
    projectId: 'development-673fa',
    storageBucket: 'development-673fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC85Y7n624pqF_oG38RkIl2wNQKpj7YDGA',
    appId: '1:717510301151:ios:6c35224b0c0e0137dae06a',
    messagingSenderId: '717510301151',
    projectId: 'development-673fa',
    storageBucket: 'development-673fa.firebasestorage.app',
    iosBundleId: 'com.example.linkVerse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC85Y7n624pqF_oG38RkIl2wNQKpj7YDGA',
    appId: '1:717510301151:ios:6c35224b0c0e0137dae06a',
    messagingSenderId: '717510301151',
    projectId: 'development-673fa',
    storageBucket: 'development-673fa.firebasestorage.app',
    iosBundleId: 'com.example.linkVerse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHxzBf7AzcoK9hW7YrUoL9PNimLZGr2Ck',
    appId: '1:717510301151:web:41723d7a27af49f8dae06a',
    messagingSenderId: '717510301151',
    projectId: 'development-673fa',
    authDomain: 'development-673fa.firebaseapp.com',
    storageBucket: 'development-673fa.firebasestorage.app',
  );
}
